# keine Dupletten, deshalb "distinct":
select distinct ?class
where 
{ 
  # ueber alle Graphen...
  graph ?g
  { 
    # alle Dinge, die mit irgendetwas {genannt ?class} in der Beziehung "rdf:type" stehen:
	?s rdf:type ?class .

  }
}
